# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
branches:
  only:
    - master
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/OKBluetooth.xcworkspace -scheme OKBluetooth-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --allow-warnings

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 3